config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{PluginRoutes.all_locales}/, :defaults => {} do
    # frontend
    namespace :plugins do
      namespace 'ecommerce' do
        controller :front do
          get 'login'
          get 'cart_rescue'
          post 'login' => :do_login
          get 'register'
          post 'register' => :do_register
        end

        scope :checkout, as: :checkout do
          controller 'front/checkout' do
            get 'success_paypal'
            get 'cancel_paypal'
            post 'pay_by_bank_transfer'
            post 'pay_by_credit_card'
            post 'pay_by_authorize_net'
            post 'pay_by_stripe'
            post 'pay_by_paypal'
            post 'pay_by_on_delivery'
          end
        end

        get 'checkout' => 'front/checkout#index'
        post 'checkout/step_address' => 'front/checkout#step_address'
        post 'checkout/step_shipping' => 'front/checkout#step_shipping'
        get 'checkout/cart' => 'front/checkout#cart_index'
        get 'checkout/complete_free_order' => 'front/checkout#complete_free_order'
        post 'checkout/cart/add' => 'front/checkout#cart_add'
        post 'checkout/cart/update' => 'front/checkout#cart_update'
        delete 'checkout/cart/remove' => 'front/checkout#cart_remove'
        post 'res_coupon' => 'front/checkout#res_coupon'
        get 'orders' => 'front/orders#index'
        get 'orders/:order/show' => 'front/orders#show', as: :order_show
      end
    end
  end

  #Admin Panel
  scope 'admin', as: 'admin' do
    namespace 'plugins' do
      namespace 'ecommerce' do
        get 'index' => 'admin#index'
        get 'product_attributes' => 'admin#product_attributes'
        post 'product_attributes' => 'admin#save_product_attributes'
        resources :orders, controller: 'admin/orders' do
          get 'mark_accepted'
          get 'resend_email'
          get 'mark_bank_confirmed'
          post 'mark_shipped'
          post 'mark_canceled'
        end
        resources :payment_methods, controller: 'admin/payment_methods'
        resources :shipping_methods, controller: 'admin/shipping_methods' do
          resources :prices, controller: 'admin/prices'
        end
        resources :coupons, controller: 'admin/coupons'
        resources :tax_rates, controller: 'admin/tax_rates'
        get 'settings' => 'admin/settings#index'
        post 'settings/saved' => 'admin/settings#saved'
      end
    end
  end

  # main routes
  #scope 'ecommerce', module: 'plugins/ecommerce/', as: 'ecommerce' do
  #  Here my routes for main routes
  #end
end

app/views/post_types/commerce/_cart_widget.html.erb
<div class="row" style="min-height: 64px">
    <div class="col-md-9">
        <%= raw ecommerce_draw_breadcrumb %>
    </div>

    <div class="col-md-3">
        <div class="well shopping_cart_box">
            <% @cart ||= e_current_cart %>
            <h4><%= t('.shopping_cart', default: 'Shopping Cart') %></h4>
            <p><%= t('.total_items', default: '(%{qty}) items', qty: @cart.items_total) %>, <%= t('.total', default: 'Total') %>: <%= @cart.the_total_amount %></p>
            <span>
                <a href="<%= cama_ecommerce_post_type.the_url %>" class="btn btn-default btn-xs"><%= t('.products_list', default: 'Products list') %></a>
                <% if (@cart.items_total > 0) %>
                    <a href="<%= plugins_ecommerce_checkout_cart_path %>" class="btn btn-warning btn-xs"><%= t('.purchase', default: 'Purchase') %></a>
                <% end %>
                <a href="<%= plugins_ecommerce_orders_path %>" class="btn btn-success btn-xs"><%= t('.my_orders', default: 'My Orders') %></a>
            </span>
        </div>
    </div>
</div>
<div class="clearfix">
    <%= render partial: "/camaleon_cms/flash_messages.html.erb", locals:{ flash: (flash[:cama_ecommerce] || {}).with_indifferent_access} %>
</div>

app/views/post_types/commerce/_post_list_item.html.erb
<div class="col-sm-6 col-md-4 post-list-item">
    <div class="thumbnail">
        <%= raw post.the_link_thumb({}, {style: "height: 200px; width: 100%; display: block;"}) %>
        <div class="caption">
            <h4 id="thumbnail-label">
                <a href="<%= post.the_url %>"><%= post.the_title %> (<i class="fa fa-cart"></i> <%= post.the_price %>)</a>
            </h4>
            <small class="" style="display: block;"><%= post.the_created_at %></small>
            <hr>
            <p><%= raw post.the_excerpt %> <%= post.the_edit_link %></p>
        </div>
    </div>
</div>

app/views/post_types/commerce/_product_info.html.erb
<h1><%= product.the_title %> <%= product.the_edit_link %></h1>
<h3>
    <%= t('plugins.ecommerce.single.sku', default: 'SKU') %>: <span id="product_sku"><%= product.the_sku %></span>
    <span class="pull-right"><%= raw product.the_featured_status %></span>
</h3>
<h4><span id="product_price"><%= product.the_price %></span> <span class="pull-right"><%= raw product.the_stock_status %></span></h4>
<hr/>
<p><%= product.the_excerpt %></p>
<hr/>
<%= form_tag(plugins_ecommerce_checkout_cart_add_path, :method => "post", :class => "form") do %>
    <% if product.is_variation_product? %>
        <div class="form-group">
            <%= label_tag :variation_id %>
            <select class="form-control required" name="variation_id" id="product_variation_id">
                <% product.product_variations.each_with_index do |variation, index| %>
                    <option data-sku="<%= variation.sku %>" <%= 'selected' if params[:variation_id].to_s == variation.id.to_s %> <%= 'data-disabled="true"' if !product.in_stock?(variation.id) %> data-price="<%= product.the_price(variation.id) %>" value="<%= variation.id %>"><%= product.the_variation_title(variation.id) %></option>
                <% end %>
            </select>
        </div>
        <script>
            jQuery(function(){
                var panel = $('#product_view');
                panel.find('#product_variation_id').change(function(){
                    var op = $(this).find('option:selected');
                    panel.find('#product_sku').html(op.attr('data-sku'));
                    panel.find('#product_price').html(op.attr('data-price'));
                    panel.find('#e_add_to_cart_field_group input, button').prop('disabled', !!op.attr('data-disabled'))
                    panel.find('#ecommerce-product-slider .carousel-indicators li:eq('+$(this).children().index(op)+')').click();
                }).trigger('change');
            });
        </script>
    <% end %>
    <% if product.in_stock? %>
        <div class="input-group" id="e_add_to_cart_field_group">
            <span class="input-group-addon"><%= t('plugins.ecommerce.single.qty', default: 'Qty') %></span>
            <%= number_field :cart, :qty, class: 'form-control', value: 1, min: 0 %>
            <%= hidden_field :cart, :product_id, value: product.id %>
            <span class="input-group-btn"><button class="btn btn-default" type="submit"><i class="fa fa-shopping-cart"></i> <%= t('plugins.ecommerce.single.add_to_cart', default: 'Add to cart') %></button></span>
        </div>
    <% else %>
        <p><%= t('plugins.ecommerce.single.noavailable_items', default: 'No items available') %></p>
    <% end %>
<% end %>

app/views/post_types/commerce/single.html.erb
<% args={custom_slider: nil, custom_footer: nil, extra_footer: nil, custom_sidebar: nil, product: @post}; hooks_run('ecommerce_product_page', args) # permit custom footer %>
<%= render 'post_types/commerce/cart_widget' %>
<div class="row">
    <div class="col-md-9 post-view">
        <article class="post-content" id="product_view">
            <div class="row">
                <div class="col-md-6">
                    <% unless args[:custom_slider].present? %>
                        <div id="ecommerce-product-slider" class="carousel slide" data-ride="carousel" data-interval="false">
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                                <% @post.the_photos.each_with_index do |pthoto, index| %>
                                    <li data-target="#ecommerce-product-slider" data-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>"></li>
                                <% end %>
                            </ol>

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner" role="listbox">
                                <% @post.the_photos.each_with_index do |pthoto, index| %>
                                    <div class="item <%= 'active' if index == 0 %>">
                                        <img src="<%= pthoto %>" class="center-block">
                                    </div>
                                <% end %>
                            </div>

                            <!-- Controls -->
                            <a class="left carousel-control" href="#ecommerce-product-slider" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left fa fa-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#ecommerce-product-slider" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right fa fa-chevron-right " aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    <% else %>
                        <%= raw args[:custom_slider] %>
                    <% end %>
                </div>

                <div class="col-md-6">
                    <%= render 'post_types/commerce/product_info', product: @post %>
                </div>
            </div>

            <% unless args[:custom_footer].present? %>
                <div class="row">
                    <div class="col-md-12">
                        <h3><%= t('plugins.ecommerce.single.descr', default: 'Description') %></h3>
                        <div class="item-content">
                            <%= raw @post.the_content %>
                        </div>
                    </div>
                    <% if (attrs = @post.the_attribute_fields('ecommerce_attrs').to_a).present? && attrs.map{|k,v| v.present? }.any? %>
                        <div class="col-md-12">
                            <h3><%= t('plugins.ecommerce.single.attrs', default: 'Attributes') %></h3>
                            <table class="table table-bordered">
                                <% attrs.each_with_index do |attr, index| %>
                                    <tr>
                                        <td><strong><%= attr['attr'].to_s.translate %></strong></td>
                                        <td><%= attr['value'].to_s.translate %></td>
                                    </tr>
                                <% end %>
                            </table>
                        </div>
                    <% end %>
                </div>
            <% else %>
                <%= raw args[:custom_footer] %>
            <% end %>
            <%= raw args[:extra_footer] if args[:extra_footer].present? %>
        </article>
    </div>
    <div class="col-md-3">
        <% unless args[:custom_sidebar].present? %>
            <%= render partial: 'partials/sidebar', locals: {post: @post, skip_fields: true} %>
        <% else %>
        <%= raw args[:custom_sidebar] %>
        <% end %>
    </div>
</div>