config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{PluginRoutes.all_locales}/, :defaults => {} do
    # frontend
    namespace :plugins do
      namespace 'ecommerce' do
        controller :front do
          get 'login'
          get 'cart_rescue'
          post 'login' => :do_login
          get 'register'
          post 'register' => :do_register
        end

        scope :checkout, as: :checkout do
          controller 'front/checkout' do
            get 'success_paypal'
            get 'cancel_paypal'
            post 'pay_by_bank_transfer'
            post 'pay_by_credit_card'
            post 'pay_by_authorize_net'
            post 'pay_by_stripe'
            post 'pay_by_paypal'
            post 'pay_by_on_delivery'
          end
        end

        get 'checkout' => 'front/checkout#index'
        post 'checkout/step_address' => 'front/checkout#step_address'
        post 'checkout/step_shipping' => 'front/checkout#step_shipping'
        get 'checkout/cart' => 'front/checkout#cart_index'
        get 'checkout/complete_free_order' => 'front/checkout#complete_free_order'
        post 'checkout/cart/add' => 'front/checkout#cart_add'
        post 'checkout/cart/update' => 'front/checkout#cart_update'
        delete 'checkout/cart/remove' => 'front/checkout#cart_remove'
        post 'res_coupon' => 'front/checkout#res_coupon'
        get 'orders' => 'front/orders#index'
        get 'orders/:order/show' => 'front/orders#show', as: :order_show
      end
    end
  end

  #Admin Panel
  scope 'admin', as: 'admin' do
    namespace 'plugins' do
      namespace 'ecommerce' do
        get 'index' => 'admin#index'
        get 'product_attributes' => 'admin#product_attributes'
        post 'product_attributes' => 'admin#save_product_attributes'
        resources :orders, controller: 'admin/orders' do
          get 'mark_accepted'
          get 'resend_email'
          get 'mark_bank_confirmed'
          post 'mark_shipped'
          post 'mark_canceled'
        end
        resources :payment_methods, controller: 'admin/payment_methods'
        resources :shipping_methods, controller: 'admin/shipping_methods' do
          resources :prices, controller: 'admin/prices'
        end
        resources :coupons, controller: 'admin/coupons'
        resources :tax_rates, controller: 'admin/tax_rates'
        get 'settings' => 'admin/settings#index'
        post 'settings/saved' => 'admin/settings#saved'
      end
    end
  end

  # main routes
  #scope 'ecommerce', module: 'plugins/ecommerce/', as: 'ecommerce' do
  #  Here my routes for main routes
  #end
end

app/models/plugins/ecommerce/attribute.rb
class Plugins::Ecommerce::Attribute < ActiveRecord::Base
  self.table_name='plugins_ecommerce_attributes'
  belongs_to :site
  has_many :values, class_name: 'Plugins::Ecommerce::Attribute', foreign_key: :parent_id, dependent: :destroy
  belongs_to :product_attribute, class_name: 'Plugins::Ecommerce::Attribute', foreign_key: :parent_id
  scope :only_group, ->{ where(parent_id: nil) }
  scope :only_value, ->{ where.not(parent_id: nil) }
  default_scope ->{ order(position: :ASC) }
  def translated_values
    values.select(:id, :label, :key).map{|item| item.label = item.label.to_s.translate; item }
  end
end

app/models/plugins/ecommerce/coupon.rb
class Plugins::Ecommerce::Coupon < CamaleonCms::TermTaxonomy
  default_scope { where(taxonomy: :ecommerce_coupon) }
  belongs_to :site, :class_name => "CamaleonCms::Site", foreign_key: :parent_id
  scope :actives, -> {where(status: '1')}

  def used_times_exceeded?
    (used_applications + 1) > allowed_applications
  end

  def mark_as_used(user = nil)
    set_option('used_applications', used_applications + 1)
  end

  def used_applications
    get_option('used_applications', 0).to_i
  end

  def allowed_applications
    get_option('allowed_applications', 0).to_i
  end

  def expired?
    d = get_option('expirate_date', '')
    if d.present?
      "#{d} 23:59:59".to_datetime.to_i < Time.current.to_i
    else
      false
    end
  end

  def min_cart_total
    get_option('min_cart_total', '')
  end

  def valid_min_price?(price)
    !min_cart_total.present? || min_cart_total.to_i <= price
  end

  def active?
    status.to_s == '1'
  end

end

app/models/plugins/ecommerce/coupon_decorator.rb
=begin
  Camaleon CMS is a content management system
  Copyright (C) 2015 by Owen Peredo Diaz
  Email: owenperedo@gmail.com
  This program is free software: you can redistribute it and/or modify   it under the terms of the GNU Affero General Public License as  published by the Free Software Foundation, either version 3 of the  License, or (at your option) any later version.
  This program is distributed in the hope that it will be useful,  but WITHOUT ANY WARRANTY; without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  See the  GNU Affero General Public License (GPLv3) for more details.
=end
class Plugins::Ecommerce::CouponDecorator < CamaleonCms::TermTaxonomyDecorator
  delegate_all

  # Define presentation-specific methods here. Helpers are accessed through
  # `helpers` (aka `h`). You can override attributes, for example:
  #
  #   def created_at
  #     helpers.content_tag :span, class: 'time' do
  #       object.created_at.strftime("%a %m/%d/%y")
  #     end
  #   end

  def the_code
    object.slug.to_s.upcase
  end

  def the_amount
    opts = object.options
    case opts[:discount_type]
      when 'percent'
        "#{opts[:amount].to_f}%"
      when 'money'
        "#{the_symbol} #{opts[:amount].to_f}"
      else
        "Free"
    end
  end

  def the_symbol
    opts = object.options
    case opts[:discount_type]
      when 'percent'
        "%"
      when 'money'
        h.current_site.current_unit
      else
        ""
    end
  end

  def the_status
    opts = object.options
    if "#{opts[:expirate_date]} 23:59:59".to_datetime.to_i < Time.now.to_i
      "<span class='label label-danger'>#{I18n.t('plugin.ecommerce.table.expired')} </span>"
    elsif object.status.to_s.to_bool
      "<span class='label label-success'>#{I18n.t('plugin.ecommerce.active')} </span>"
    else
      "<span class='label label-default'>#{I18n.t('plugin.ecommerce.not_active')} </span>"
    end

  end
end

app/models/plugins/ecommerce/legacy_order.rb
## not used anymore (DEPRECATED)
class Plugins::Ecommerce::LegacyOrder < CamaleonCms::TermTaxonomy
  default_scope { where(taxonomy: :ecommerce_order) }
  has_one :details, class_name: "Plugins::Ecommerce::OrderDetail", foreign_key: :order_id, dependent: :destroy
  has_many :products, foreign_key: :objectid, through: :term_relationships, :source => :objects

  def payment_method
    Plugins::Ecommerce::PaymentMethod.find_by_id get_meta("payment")[:payment_id]
  end

  def payment
    payment = get_meta("payment")
    get_meta("pay_#{payment[:type]}".to_sym)
  end

  def shipping_method
    Plugins::Ecommerce::ShippingMethod.find_by_id get_meta("payment", {})[:shipping_method]
  end
end

app/models/plugins/ecommerce/order_detail.rb
## not used anymore (DEPRECATED)
class Plugins::Ecommerce::OrderDetail < ActiveRecord::Base
  self.table_name = "plugins_order_details"
  belongs_to :order, class_name: "Plugins::Ecommerce::Order", foreign_key: :order_id
end

app/models/plugins/ecommerce/product_item.rb
class Plugins::Ecommerce::ProductItem < ActiveRecord::Base
  include CamaleonCms::Metas
  self.table_name = 'plugins_ecommerce_products'
  belongs_to :cart, class_name: 'Plugins::Ecommerce::Cart', foreign_key: :order_id, touch: true
  belongs_to :order, class_name: 'Plugins::Ecommerce::Order'
  belongs_to :product, foreign_key: :product_id, class_name: 'CamaleonCms::Post'
  belongs_to :product_variation, class_name: 'Plugins::Ecommerce::ProductVariation', foreign_key: :variation_id

  def sub_total
    p = self.product.decorate
    (p.price(self.variation_id) + p.tax(self.variation_id)) * self.qty
  end
end

app/controllers/plugins/ecommerce/admin/coupons_controller.rb
class Plugins::Ecommerce::Admin::CouponsController < Plugins::Ecommerce::AdminController
  before_action :set_order, only: ['show','edit','update','destroy']

  def index
    @coupons = current_site.coupons.paginate(:page => params[:page], :per_page => current_site.admin_per_page)
  end

  def new
    @coupon = current_site.coupons.new
    add_breadcrumb("#{t('plugins.ecommerce.new')}")
    render 'form'
  end

  def show
  end

  def edit
    add_breadcrumb("#{t('camaleon_cms.admin.button.edit')}")
    render 'form'
  end

  def create
    @coupon = current_site.coupons.new(coupons_permit_data)
    if @coupon.save
      @coupon.set_meta('_default', params[:options])
      flash[:notice] = t('camaleon_cms.admin.post_type.message.created')
      redirect_to action: :index
    else
      render 'form'
    end
  end

  def update
    if @coupon.update(coupons_permit_data)
      @coupon.set_meta('_default', params[:options])
      flash[:notice] = t('camaleon_cms.admin.post_type.message.updated')
      redirect_to action: :index
    else
      render 'form'
    end
  end




  private

  def coupons_permit_data
    params.require(:plugins_ecommerce_coupon).permit!
  end
  def set_order
    @coupon = current_site.coupons.find(params[:id])
  end

end

app/controllers/plugins/ecommerce/admin/orders_controller.rb
class Plugins::Ecommerce::Admin::OrdersController < Plugins::Ecommerce::AdminController
  before_action :set_order, except: [:index, :new] #, only: ['show', 'edit', 'update', 'destroy']
  before_action :set_order_bread

  def index
    @q = current_site.orders.order('received_at desc').ransack(params[:q])
    @orders = @q.result.paginate(:page => params[:page], :per_page => current_site.admin_per_page)
  end

  def show
    @order = @order.decorate
    add_breadcrumb("#{t('plugins.ecommerce.details_order', default: 'Order details')} - #{@order.slug}")
  end

  def new
    @order = current_site.orders.new
    render 'form'
  end

  def edit
    add_breadcrumb("#{t('camaleon_cms.admin.button.edit', default: 'Edit')}")
    render 'form'
  end

  def update
    hooks_run('plugin_ecommerce_before_update_order', @order)
    @order.set_meta("billing_address", params[:order][:billing_address])
    @order.set_meta("shipping_address", params[:order][:shipping_address])
    @order.set_metas(params[:metas])
    @order.update(params.require(:plugins_ecommerce_order).permit(:shipped_at))
    hooks_run('plugin_ecommerce_after_destroy_order', @order)
    flash[:notice] = "#{t('plugins.ecommerce.message.order_updated', default: 'Order Updated')}"
    redirect_to action: :show, id: params[:id]
  end

  def destroy
    hooks_run('plugin_ecommerce_before_destroy_order', @order)
    if @order.destroy
      flash[:notice] = "#{t('plugins.ecommerce.message.order_destroyed', default: 'Order Destroyed')}"
    else
      flash[:error] = "#{t('plugins.ecommerce.message.order_no_destroyed', default: 'Occurred some problems destroying the order')}"
    end
    hooks_run('plugin_ecommerce_after_destroy_order', @order)
    redirect_to action: :index
  end

  # accepted order
  def mark_accepted
    r = {order: @order}; hooks_run('plugin_ecommerce_before_accepted_order', r)
    @order.accepted!
    commerce_order_send_mail(@order, 'email_order_accepted')
    message = "#{t('plugins.ecommerce.message.order_accepted', default: 'Order Accepted')}"
    r = {order: @order, message: message}; hooks_run('plugin_ecommerce_after_accepted_order', r)
    flash[:notice] = r[:message]
    redirect_to action: :index
  end

  def mark_bank_confirmed
    if @order.on_delivery_pending?
      hooks_run('plugin_ecommerce_before_on_delivery_order', @order)
      @order.on_delivery_confirmed!
      commerce_order_send_mail(@order, 'email_order_confirmed_on_delivery')
      flash[:notice] = "#{t('plugins.ecommerce.message.order_on_delivery_confirmed', default: 'Payment on Delivery Confirmed')}"
      hooks_run('plugin_ecommerce_after_on_delivery_order', @order)
    else
      hooks_run('plugin_ecommerce_before_bank_confirm_order', @order)
      @order.bank_confirmed!
      commerce_order_send_mail(@order, 'email_order_confirmed_bank')
      flash[:notice] = "#{t('plugins.ecommerce.message.order_bank_confirmed', default: 'Pay Bank Confirmed')}"
      hooks_run('plugin_ecommerce_after_bank_confirm_order', @order)
    end
    redirect_to action: :index
  end

  # shipped order
  def mark_shipped
    hooks_run('plugin_ecommerce_before_shipped_order', @order)
    @order.shipped!(params[:consignment_number])
    commerce_order_send_mail(@order, 'email_order_shipped')
    flash[:notice] = "#{t('plugins.ecommerce.message.order_shipped', default: 'Order Shipped')}"
    hooks_run('plugin_ecommerce_after_shipped_order', @order)
    redirect_to action: :index
  end

  def mark_canceled
    hooks_run('plugin_ecommerce_before_canceled_order', @order)
    @order.canceled!
    @order.set_meta('description', params[:description])
    commerce_order_send_mail(@order, 'email_order_cancelled')
    flash[:notice] = "#{t('plugins.ecommerce.message.order_canceled', default: 'Order canceled')}"
    hooks_run('plugin_ecommerce_after_canceled_order', @order)
    redirect_to action: :index
  end

  def resend_email
    case @order.status
      when 'paid', 'bank_pending', 'on_delivery'
        commerce_order_send_mail(@order)
      when 'shipped'
        commerce_order_send_mail(@order, 'email_order_shipped')
      when 'canceled'
        commerce_order_send_mail(@order, 'email_order_cancelled')
      else
        flash[:error] = "#{t('plugins.ecommerce.message.unknown_status', default: 'Unknown Status')}"
        redirect_to action: :index
        return
    end
    flash[:notice] = "#{t('plugins.ecommerce.message.order_email_resent', default: 'Order Email Resent')}"
    redirect_to action: :index
  end

  private
  def set_order
    @order = current_site.orders.find_by_slug(params[:id] || params[:order_id]).decorate
  end

  def set_order_bread
    add_breadcrumb I18n.t("plugins.ecommerce.orders", default: 'Orders'), admin_plugins_ecommerce_orders_path
  end

end

app/controllers/plugins/ecommerce/admin/payment_methods_controller.rb
class Plugins::Ecommerce::Admin::PaymentMethodsController < Plugins::Ecommerce::AdminController
  before_action :set_order, only: ['show','edit','update','destroy']

  def index
    @payment_methods = current_site.payment_methods.paginate(:page => params[:page], :per_page => current_site.admin_per_page)
  end

  def new
    @payment_method = current_site.payment_methods.new
    @payment_method.status = 1
    add_breadcrumb("#{t('plugins.ecommerce.new')}")
    render 'form'
  end

  def show
    add_breadcrumb("#{t('plugins.ecommerce.table.details')}")
    @payment_method = @payment_method.decorate
  end

  def edit
    add_breadcrumb("#{t('camaleon_cms.admin.button.edit')}")
    render 'form'
  end

  def create
    @payment_method = current_site.payment_methods.new(payment_permit_data)
    if @payment_method.save
      @payment_method.set_meta('_default',params[:options])
      flash[:notice] = t('camaleon_cms.admin.post_type.message.created')
      redirect_to action: :index
    else
      render 'form'
    end
  end

  def update
    if @payment_method.update(payment_permit_data)
      @payment_method.set_meta('_default',params[:options])
      flash[:notice] = t('camaleon_cms.admin.post_type.message.updated')
      redirect_to action: :index
    else
      render 'form'
    end
  end

  private
  def payment_permit_data
    params.require(:plugins_ecommerce_payment_method).permit!
  end

  def set_order
    @payment_method = current_site.payment_methods.find(params[:id])#.decorate
  end
end

app/controllers/plugins/ecommerce/admin/prices_controller.rb
class Plugins::Ecommerce::Admin::PricesController < Plugins::Ecommerce::AdminController
  before_action :set_shipping_method

  def index
  end

  def new
    @price = {}
    add_breadcrumb("#{t('plugins.ecommerce.new')}")
    render 'form'
  end

  def show
  end

  def edit
    @price = @prices[params[:id].to_sym] || {}
    add_breadcrumb("#{t('camaleon_cms.admin.button.edit')}")
    render 'form'
  end

  def create
    _id = Time.now.to_i.to_s
    data = params[:price]
    data[:id] = _id
    @prices[_id] = data
    @shipping_method.set_meta('prices', @prices)
    flash[:notice] = t('camaleon_cms.admin.post_type.message.created')
    redirect_to action: :index
  end

  def update
    _id = params[:id]
    @price = @prices[params[:id].to_sym] || {}
    @prices[_id] = @price.merge(params[:price])
    @shipping_method.set_meta('prices', @prices)
    flash[:notice] = t('camaleon_cms.admin.post_type.message.updated')
    redirect_to action: :index
  end

  def destroy
    @prices.delete(params[:id].to_sym)
    @shipping_method.set_meta('prices', @prices)
    flash[:notice] = t('camaleon_cms.admin.post_type.message.deleted')
    redirect_to action: :index
  end



  private
  def set_shipping_method
    @shipping_method = current_site.shipping_methods.find(params[:shipping_method_id])
    add_breadcrumb(t("plugins.ecommerce.shipping_methods"))
    add_breadcrumb(@shipping_method.name)
    add_breadcrumb(t("plugins.ecommerce.shipping_prices"), admin_plugins_ecommerce_shipping_method_prices_path(params[:shipping_method_id]))
    @prices = @shipping_method.get_meta("prices", {})
  end

end

app/controllers/plugins/ecommerce/admin/settings_controller.rb
class Plugins::Ecommerce::Admin::SettingsController < Plugins::Ecommerce::AdminController
  add_breadcrumb I18n.t("plugins.ecommerce.e_commerce")
  def index
    @setting = current_site.e_settings
  end

  # save settings
  def saved
    current_site.e_settings(params[:setting])
    flash[:notice] = t('camaleon_cms.admin.post_type.message.updated')
    redirect_to action: :index
  end
end

app/views/plugins/ecommerce/front/login.html.erb
<div class="container" id="ecommerce_login_panel">
    <%= render 'post_types/commerce/cart_widget' %>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#login-form" role="tab" data-toggle="tab"><%= t('.login', default: 'Login') %></a></li>
                <li role="presentation"><a href="#register-form" role="tab" data-toggle="tab"><%= t('.register', default: 'Register') %></a></li>
            </ul>
            <div class="tab-content">
                <%= form_tag plugins_ecommerce_login_path, id: 'login-form', class: 'tab-pane active', role: 'tabpanel' do %>
                    <%= hidden_field_tag :kind_form, 'login-form' %>
                    <div class="form-group">
                        <input type="text" name="email" tabindex="1" class="form-control required" placeholder="<%= t('.email', default: 'Email') %>" value="<%= params[:email] %>">
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" tabindex="2" class="form-control required" placeholder="<%= t('.password', default: 'Password') %>">
                    </div>
                    <div class="form-group">
                        <%= button_tag t('.login', default: 'Login'), class: 'btn btn-default col-md-3', type: 'submit' %>
                        <a href="<%= cama_admin_forgot_url(return_to: site_current_url) %>" tabindex="5" class="pull-right"><%= t('.forgot', default: 'Forgot Password?') %></a>
                    </div>
                    <div class="clearfix"></div>
                <% end %>

                <%= form_for @user, url: plugins_ecommerce_register_path, html: { id: 'register-form', class: 'tab-pane', role: 'tabpanel' } do |f| %>
                    <%= render partial: 'layouts/camaleon_cms/admin/form_error', locals: {data: @user} %>
                    <%= hidden_field_tag :kind_form, 'register-form' %>
                    <div class="form-group">
                        <%= f.text_field :first_name, class: 'form-control required', tabindex: 1, placeholder: t('.full_name', default: 'Full Name') %>
                    </div>
                    <div class="form-group">
                        <%= f.text_field :email, class: 'form-control email required', tabindex: 3, placeholder: t('.email', default: 'Email address') %>
                    </div>
                    <div class="form-group">
                        <%= f.password_field :password, class: 'form-control required', tabindex: 4, placeholder: t('.password', default: 'Password') %>
                    </div>
                    <div class="form-group">
                        <%= f.password_field :password_confirmation, class: 'form-control required', equalTo: '#camaleon_cms_user_password', tabindex: 5, placeholder: t('.confirm_pass', default: 'Confirm Password') %>
                    </div>
                    <div class="form-group">
                        <%= submit_tag t('.create_account', default: 'Create account'), class: 'btn btn-default col-md-3' %>
                    </div>
                    <div class="clearfix"></div>
                <% end %>
            </div>
        </div>
    </div>
</div>
<script>
  $(function() {
    var panel = $('#ecommerce_login_panel');
    <% if params[:kind_form].present? %>
      $('#<%= params[:kind_form] %>-link', panel).click();
    <% end %>

    function do_validation(){
      $("#register-form", panel).validate();
      $("#login-form", panel).validate();
    }

    if(!$.fn.validator) $.getScript('<%= asset_url('camaleon_cms/admin/jquery.validate') %>', function(){ do_validation(); });
    else do_validation();
  });
</script>

app/views/plugins/ecommerce/front/product.html.erb
<%= render layout: 'plugins/ecommerce/layouts/ecommerce', locals: {add_breadcrumb: @post.the_breadcrumb} do %>
    <%
       @field_values = @post.get_field_values_hash
    %>
    <div class="container-fluid">
      <%#= render partial: 'partials/breadcrumb', locals: {breadcrumb: @post.the_breadcrumb} %>
      <div class="row">
        <div class="col-md-9 post-view">
          <article class="post-content">
            <div class="row">
              <div class="col-md-6">

                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                  <!-- Indicators -->
                  <ol class="carousel-indicators">
                    <% @post.the_photos.each_with_index do |pthoto, index| %>
                        <li data-target="#carousel-example-generic" data-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>"></li>
                    <% end %>
                  </ol>

                  <!-- Wrapper for slides -->
                  <div class="carousel-inner" role="listbox">

                    <% @post.the_photos.each_with_index do |pthoto, index| %>
                        <div class="item <%= 'active' if index == 0 %>">
                          <img src="<%= pthoto %>" class="center-block">
                        </div>
                    <% end %>

                  </div>

                  <!-- Controls -->
                  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left fa fa-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right fa fa-chevron-right " aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>


              </div>
              <div class="col-md-6">
                <h1><%= @post.the_title %></h1>

                <h3>SKU: <%= @post.the_sku %>  <span class="pull-right"><%= raw @post.the_featured_status %></span></h3>
                <h4><%= @post.the_price %> <span class="pull-right"><%= raw @post.the_stock_status %></span></h4>
                <hr/>
                <p><%= @post.the_excerpt %></p>
                <hr/>
                <% if @post.in_stock? %>
                    <p>Items available: <%= @post.the_qty_real %></p>
                    <% if @post.the_qty_real.to_i > 0 %>
                        <%= form_tag(plugins_ecommerce_checkout_cart_add_path, :method => "post", :class => "form") do %>
                            <div class="">
                              <label class="">Qty: </label>
                              <%= number_field :cart, :qty, value: 1, min: 0, max: @post.the_qty_real.to_i %>
                              <%= hidden_field :cart, :product_id, value: @post.id %>

                              <button type="submit" class="btn"><i class="fa fa-shopping-cart"></i><%= t('plugin.ecommerce.add_to_cart') %></button>
                            </div>
                        <% end %>
                    <% end %>
                <% end %>
              </div>
            </div>


            <div class="row">

              <div class="col-md-6">
                <h3>Description</h3>

                <div class="item-content">
                  <%= raw @post.the_content %>
                </div>
              </div>

              <% attrs = []; @field_values[:ecommerce_attrs].to_a.each { |attr| attrs << JSON.parse(attr) rescue {} } %>
              <% if attrs.present? %>
                  <div class="col-md-6">
                    <h3>Attributes</h3>
                    <table class="table table-bordered">
                      <% attrs.each do |data| %>
                          <tr>
                            <td><strong><%= data['attr'].to_s.translate %></strong></td>
                            <td><%= data['value'].to_s.translate %></td>
                          </tr>
                      <% end %>
                    </table>
                  </div>
              <% end %>
            </div>
          </article>
        </div>
        <div class="col-md-3">
          <%= render partial: 'partials/sidebar', locals: {post: @post} %>
        </div>
      </div>
    </div>
<%#= debug @field_values %>

<% end %>